name: llm_cpp_chat_app
description: "A Flutter chat application with local LLM inference."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^10.0.0
  path_provider: ^2.1.1
  provider: ^6.1.1
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  permission_handler: ^11.0.1
  lcpp: 0.2.5
  http: ^1.3.0
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3
  dartz: ^0.10.1
  equatable: ^2.0.5
  path: ^1.8.3
  dio: ^5.8.0+1
  logger: ^2.5.0
  flutter_downloader: ^1.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  change_app_package_name: ^1.5.0
  rename_app: ^1.6.2
  flutter_launcher_icons: "^0.14.3"

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
